export const MONTANA_REGIONS = [
  'Bitterroot Valley',
  'Missoula & Western Montana',
  'Flathead Valley',
  'Helena & Central Montana',
  'Bozeman & Gallatin Valley',
  'Eastern Montana',
]

export const MONTANA_COUNTIES = [
  'Beaverhead',
  'Big Horn',
  'Blaine',
  'Broadwater',
  'Carbon',
  'Carter',
  'Cascade',
  'Chouteau',
  'Custer',
  'Daniels',
  'Dawson',
  'Deer Lodge',
  'Fallon',
  'Fergus',
  'Flathead',
  'Gallatin',
  'Garfield',
  'Glacier',
  'Golden Valley',
  'Granite',
  'Hill',
  'Jefferson',
  'Judith Basin',
  'Lake',
  'Lewis and Clark',
  'Liberty',
  'Lincoln',
  'Madison',
  'McCone',
  'Meagher',
  'Mineral',
  'Missoula',
  'Musselshell',
  'Park',
  'Petroleum',
  'Phillips',
  'Pondera',
  'Powder River',
  'Powell',
  'Prairie',
  'Ravalli',
  'Richland',
  'Roosevelt',
  'Rosebud',
  'Sanders',
  'Sheridan',
  'Silver Bow',
  'Stillwater',
  'Sweet Grass',
  'Teton',
  'Toole',
  'Treasure',
  'Valley',
  'Wheatland',
  'Wibaux',
  'Yellowstone',
]

export const REGISTERED_VOTER_OPTIONS = ['Yes', 'No']

export const CAMPAIGN_EXPERIENCE_OPTIONS = [
  'Yes, local (school board, county commissioner, etc.)',
  'Yes, state level (House, Senate, State Assembly, etc.)',
  'Yes, statewide (AG, Governor, etc.)',
  'Yes, federal (Congressional)',
  'Yes, federal (Presidential)',
  'No',
]

export const HELP_OPTIONS = [
  'Host a Fundraiser',
  'Phone Banking',
  'Volunteer Coordination',
  'Digital/Social Media',
  'Door Knocking',
  'Host a Meet & Greet',
  'Event Planning',
  'Media',
]

export const AVAILABILITY_OPTIONS = [
  '1-2 hours/week',
  '3-5 hours/week',
  '5-10 hours/week',
  '10-20 hours/week',
  'Full-time',
  'Remote Help Only',
]
